# -*- coding: utf-8 -*-
"""3-CMD Activity.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-FiQaRg40tV0rlvAgCp22ntOW3GEopgf

## Welcome to the CMD activity!

In this activity, you will be making your own color magnitude diagram of the stars in Andromeda targeted by the SPLASH survey. 

As usual with Jupyter, begin by importing the packages you'll be needing by clicking on the first cell and pressing Shift+Enter. For this activity, you'll only be needing numpy and matplotlib.
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline
import matplotlib as mpl

"""This next cell is my preferred setting for making plots; I like big font and serifs! Feel free to change if you have a different preference!"""

mpl.rcParams['font.family']='serif'
mpl.rcParams['font.size']=14

"""This function initializes the CMD plot and labels the axes. No data is plotted in this function. You don't need to modify this function."""

def InitializePlot():
    plt.clf()
    f= plt.figure(figsize=(8,8))
    plt.xlim(-1, 9)
    plt.ylim(24, 18)
    plt.xlabel('F475W - F814W (mag)')
    plt.ylabel('F814W (mag)')

"""This function writes a catalog. It takes as arguments the name of the file,  the different quantities you want to put in the catalog, and the names of these quantities. You do not need to modify this function."""

def WriteCatalog(catalogName, params, paramNameString):
    #first, create and open the text file for writing. Choose a name: 
    catalog = open(catalogName, 'w')

    #write first row
    catalog.write('# ' + paramNameString + '\n')

    #then, loop through stars and write 1 row for each star.
    for i in range(len(params[0])): #loop over stars
        for j in range(len(params)): #loop over parameters (ra, dec, v, verr,...)
            catalog.write(str(params[j][i]))
            catalog.write(' ')
        catalog.write('\n')
    catalog.close()

    return

def WriteCatalog(catalogName, params, paramNameString):
    with open(catalogName) as catalog:
        for i in range(len(params[0])): #loop over stars
            for j in range(len(params)): #loop over parameters (ra, dec, v, verr,...)
                catalog.write(str(params[j][i]))
                catalog.write(' ')
            catalog.write('\n')

"""Okay, now that we have all our packages imported, we are ready to get to the science! The first thing we need to do is read in the file that contains all our data. This file contains the coordinates (ra, dec, xi, eta), the magnitudes (in two different bandpasses), and the velocities of all our stars (we will talk more about velocities next!). 

As we discussed, the color of the star is a very useful and important quantity; we define the array for "color" below.
"""

ra, dec, xi, eta, f475w, f814w, v, verr = np.loadtxt('../data/keck_hst_data.txt', unpack = True)
color = f475w - f814w

"""Now we can plot a color magnitude diagram of all the objects in our sample:"""

f = InitializePlot()
plt.scatter(color, f814w, c = 'gray', s = 3, edgecolors = 'none')

"""Now that we have our CMD, we want to separate out the stars of different types: main sequence (MS) stars, red giant branch (RGB) stars, and asymptotic giant branch (AGB) stars. The below cell selects the main sequence stars and plots them in blue on top of the CMD. It then writes a catalog in your "data" folder that contains the information only for the MS stars.

What you'll be doing is adapting and adding to the code below to do the same for the RGB and AGB stars. You want to color code the RGB and AGB stars on the plot, add the labels "AGB" and "RGB" to the plot, and write the RGB and AGB catalogs.

First run the cell to see the plot produced. Then, "uncomment" (meaning remove the lines with # signs--the # sign tells Python not to run the line) the line that begins "rgb=" and replace a, h, and k with numbers. To decide what numbers to choose, use the "DividedCMD" figure in your "plots" folder for inspiration. Plot your selected RGB stars, and then do the same for the AGB stars.
"""

#========From here on is the part that you're going to copy and
#adapt for the RGB and AGB stars===============================

#Where condition to isolate main sequence stars
ms = (color < 1.75) & (f814w < 23)

#Plot MS stars in blue on the plot and label that region 
f = InitializePlot()
plt.scatter(color, f814w, c = 'gray', s = 3, edgecolors = 'none')
plt.scatter(color[ms], f814w[ms], c = 'blue', edgecolors = 'none', s = 5)
plt.text(-0.5, 23.5, 'MS', color = 'blue', size = 16)

#Write a text file containing information for MS stars by calling the
#WriteCatalog function on the stars that satisfy the MS condition.
#You shouldn't modify the WriteCatalog function itself;
#only copy and modify the line below for the AGB and RGB groups. 
WriteCatalog('../data/MScatalog.txt',
             [ra[ms], dec[ms], xi[ms], eta[ms], f475w[ms], f814w[ms], v[ms], verr[ms]],
             'RA DEC XI ETA F475W F814W V VERR')

#==============================================================
#Replace a, h, and k with numbers, and see what happens 
#rgb= (color > 1.75 ) & (f814w > a*(color-h)**2.+k)
##Add the RGB stars to the plot!

#Write the catalog here when you're happy with your selection!
#Then, add the AGB stars to the plot and write an AGB catalog as well!
#==============================================================

# Determine what fraction of the entire catalog are selected by the MS, RGB, and AGB criteria
nstars = len(color)
print('Fraction of stars on the MS: {0:.3f}'.format(np.sum(ms)/nstars))
print('Fraction of stars on the RGB: {0:.3f}'.format(np.sum(rgb)/nstars))
print('Fraction of stars on the AGB: {0:.3f}'.format(np.sum(agb)/nstars))
selected = ms | rgb | agb
print('Fraction of stars not selected: {0:.3f}'.format(np.sum(~selected)/nstars))

