# -*- coding: utf-8 -*-
"""6-Velocity Dispersion Activity.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jeS-hhvMGnLijSOdxkawhtEQrMoxotv_

In this activity, you are going to be making dispersion maps of Andromeda for the 3 different types of stars you learned about in week 1: Main Sequence (MS) stars, Red Giant Branch (RGB) stars, and Asymptotic Giant Branch (AGB) stars. We want to understand what these three maps tell us about the history of the Andromeda galaxy. 

As usual, begin by running the first cell to import all necessary functions from numpy and matplotlib:
"""

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
# %matplotlib inline
import numpy as np

"""Here, we are introducing the function "show_map." You may recognize it from last week's activity about simulated disks. Run the below cell--you do not need to make any edits here."""

def show_map(xi, eta, quantity, label, fileName):
    ax = plt.axes(aspect = 'equal')
    ax.set_xlabel('xi (kpc)')
    ax.set_ylabel('eta (kpc)')
    ax.set_title('Dispersion of Real Data')
    tt = ax.scatter(xi, eta, c = quantity, edgecolors = 'none', s = 2, vmin=40., vmax=160.)
    ax.set_xlim(1, 0)
    plt.colorbar(tt, label='Velocity Dispersion (km/s)')
    plt.savefig(fileName)

"""This next function is where we are calculating the dispersion. Fill in the incomplete lines of code below. To search for math help in python, Google "numpy" followed by the thing you want to do."""

def get_dispersion(x, z, v, circleSize=300./3600.):
    #initialize dispersion to all zeros
    dispersion = np.zeros(len(x))

    #Loop over all items in list
    for i in range(len(x)):
        #get coordinates of the item of interest
        thisX = x[i]
        thisZ = z[i]

        #calculate array of distances to this star
        dist =
        
        #pick out stars that are closer than circleSize to the star
        keep =

        #calculate the velocity dispersion of those stars; assign to the ith element
        #of the array "dispersion"
        dispersion[i] =
        
    return dispersion

"""The following lines of code are going to call the above two functions to generate the plots we are interested in. It is going to read in the catalogs that you created in the first activity (the CMD activity). If you do not have copies of these catalogs in your "data" folder, be sure to download them from Schoology.


## Once you've generated your figure, play with the parameter "circleSize" in get_dispersion. 
What happens when you make circleSize=100./3600.? What about 3600./3600.? Work with your partner to try to explain the differences between the two plots. Change the value of circleSize=300./3600. before you continue.
"""

#Read data
xi, eta, v = np.loadtxt('../data/MScatalog.txt', unpack = True, usecols = (2, 3, 6))

##IMPORTANT: THESE NEXT FEW LINES ACCOUNT FOR A BUG IN THE CATALOGS.
##MAKE SURE YOU INCLUDE THESE LINES IN YOUR AGB AND RGB CODES.
#___________________________
keep=(np.abs(v) < 1000.)
xi=xi[keep]
eta=eta[keep]
v=v[keep]
#___________________________

#Calculate dispersion
ms_sigma = get_dispersion(xi, eta, v)
#print np.min(sigma), np.max(sigma), np.mean(sigma)

#Generate velocity map
show_map(xi, eta, ms_sigma, 'Velocity dispersion (km/s)', '../plots/MS_dispersion_map.png')

#Fill in your code for the AGB stars here!

#Fill in your code for the RGB stars here!

"""After you’ve made all 3 maps, open up all 3 plots together (they are saved in your plots foloder). Look at them next to each other. What do you observe about these 3 maps? What do they have in common, and how are they different?

Now, plot histograms for the velocity dispersions of the 3 types of stars. If you aren’t sure what a histogram is, begin by Googling that! Hint: to search for plotting help in python, Google “matplotlib” followed by the thing you want to do (for example, if I wanted to make a plot of a line, I would Google “matplotlib plot line”).
"""

#Put your histogram plotting code here!

"""Finally, compute the median velocity dispersion for each of the 3 age groups. Don't be afraid to use Google!"""

#Compute and print the median values here!

"""Do your median values and histograms agree with your interpretation of the 3 maps? """

